feat: IDP-1766-crittografare-il-pin-della-cie
pagopa/idpay-payment-instrument pull request #154
Opened 2023-10-03 16:06 UTC by LarissaASLeite

#### Description

#### List of Changes
- Creation PinBlock
- Hash PinBlock

#### Motivation and Context

#### How Has This Been Tested?

- Pre-Deploy Test
    - [x] Unit
    - [ ] Integration (Narrow)
- Post-Deploy Test
    - [ ] Isolated Microservice
    - [x] Broader Integration
    - [ ] Acceptance
    - [ ] Performance & Load

#### Types of changes

- [ ] PATCH - Bug fix (backwards compatible bug fixes)
- [x] MINOR - New feature (add functionality in a backwards compatible manner)
- [ ] MAJOR - Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-03 16:58 UTC, antonioT90 requested changes

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/model/PaymentInstrumentCode.java
> +  private String secondFactor;
why are calling it secondFactor and not fakeNIS?

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/EncryptCodeServiceImpl.java
> +        throw new PaymentInstrumentException(400, "Pin length it's not valid");
```suggestion
        throw new PaymentInstrumentException(400, "Pin length is not valid");
```

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/EncryptCodeServiceImpl.java
> +      log.info("[{}] pinBlock generated successfully", GENERATE_PIN_BLOCK);
you are logging too much: we are not interested to have an INFO for operation inside each step.
make all inner logs DEBUG and let just one INFO.
eg: one INFO to log the complete pinBlock generation, and a DEBUG to locate create, hash, cipher operations

ps: the performanceLog is already an INFO log

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
> +    String idpayCode = encryptCodeService.encryptIdpayCode(clearCode, secondFactor, salt);
let's give more meaningfull names
```suggestion
    String hashedPinBlock= encryptCodeService.encryptIdpayCode(clearCode, secondFactor, salt);
```

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/EncryptCodeServiceImpl.java
> +  public String encryptIdpayCode(String code, String secondFactor, String salt) {
let's use more meaningful names
```suggestion
  public String buildHashedPinBlock(String code, String secondFactor, String salt) {
```

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
> +  private String generateSaltOrSecondFactor(int length) {
```suggestion
  private String generateRandomBase64String(int length) {
```

2023-10-03 16:58 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/payment/instrument/service/idpaycode/PaymentInstrumentCodeServiceImpl.java
> +  // TODO Put length like dynamic variable?
resolve this TODO before to merge

2023-10-04 08:00 UTC, LarissaASLeite commented on src/main/java/it/gov/pagopa/payment/instrument/model/PaymentInstrumentCode.java
> +  private String secondFactor;
to standardize with the ms MIL

2023-10-04 17:55 UTC, antonioT90 requested changes

2023-10-05 08:17 UTC, antonioT90 approved these changes

2023-10-05 08:18 UTC, frtrinca approved these changes

2023-10-05 08:19 UTC, merged